### ISSUE TITLE
How to get it working

### ISSUE THREAD

**Issue by mackintosh5** [Linesight-RL/linesight#15]

**Comment by mackintosh5** [comment]
I have gotten up to the point where you need to create checkpoints for the map, which has taken 3 days. the instructions don't work or don't describe things enough.

**Comment by pb4git** [comment]
Hello,
As stated in the readme: 

> Please note: This project is a research work-in-progress and may not receive active support for setup or usage.

The code will be generally difficult to use if you are not familiar with Python programming, neural networks and reinforcement learning.

We have opened a "Linesight" channel on Donadigo's "Trackmania Tool Assisted" Discord server (links in the readme). You may join the channel and hope others will be able to help you. If you end up finding a way to make the code work, you may propose improvements to the documentation as @terafear kindly did.

Regards,

**Comment by pb4git** [comment]
I'm closing this issue as version 3 has now been released.
