### ISSUE TITLE
Warning capturing interations=1, parsed_time=71110, sim_state_race_time=0

### ISSUE THREAD

**Issue by Lukasek29** [Linesight-RL/linesight#25]
Hi, when I wanna train an ai it shows this
![Bez názvu](https://github.com/pb4git/trackmania_rl_public/assets/134734420/1e02a712-f4a0-4344-89e3-5034ce9771e4)
Warning capturing interations=(number that increases), parsed_time=71110, sim_state_race_time=0

Only what happens that game speed changes to 0 (freeze game) and changes POF 3 or 1, not sure, and do nothing only spaming these same things on CMD

BTW I use laptop intel uhd graphics 630 4gb
I also have gtx 1050 2gb in it but not sure if it will work with 2gb vram

**Comment by pb4git** [comment]
I'm closing this issue as version 3 has now been released.
