### ISSUE TITLE
File not created, and load map?

### ISSUE THREAD

**Issue by NumseBacon** [Linesight-RL/linesight#3]
Hello! 

When using "observe_manual_run_to_extract_checkpoints.py" and driving the map it says couldnt be created due to no map.npy existing. I just made the folder "maps" myself and it seems it works now. Just letting you know about this.

And regarding the edit the location of map.npy at train.py, i dont quite understand how/where to do this? Also seems like map_name should be used, but that isnt mentioned? I think im doing it wrong, since i get a "IndexError: list index out of range" error

Also thanks for this awesome projekt!

**Comment by DocOnes** [comment]
Hello ! 

To edit the location of map.npy at train.py, i wrote it like this :"zone_centers = np.load(str(base_dir /"maps"/ f"{map_name}.npy"))" and it seem to work but my file name is map so i changed the value of map_name to "map"

I hope this has helped you ! I'm not sure if this is the right solution, so it may not work.

**Comment by pb4git** [comment]
I think DocOnes answered properly. The reason is that we train on several different maps, hence the need to save the checkpoints under different file names.

**Comment by pb4git** [comment]
I'm closing this issue as version 3 has now been released.
