### ISSUE TITLE
TMInterface folder does not exist

### ISSUE THREAD

**Issue by ThatGuyCalledJesse** [Linesight-RL/linesight#30]
The program assumes there is a `Documents/TMInterface` folder, but there isn't. I altered nothing, it just isn't there

**Comment by pb4git** [comment]
The only place where a TMInterface folder exists in the codebase is in [user_config.py](https://github.com/Linesight-RL/linesight/blob/811940f0f1df90d85599e11f1c41806bd7a1705e/config_files/user_config.py#L16).

It is expected that users adjust the contents of user_config.py to match their setup. In your case, you'd need to find where this TMInterface folder is located and change the content of user_config.py accordingly. 

The [documentation](https://linesight-rl.github.io/linesight/build/html/) lists all steps required to setup the project.

**Comment by ThatGuyCalledJesse** [comment]
There is no TMInterface folder that contains a plugin folder. When searching on both of my disks, it just isn't there. I have tminterface installed

**Comment by ThatGuyCalledJesse** [comment]
I figured it out, my bad
