### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\pavan\\Documents\\TMInterface\\Plugins\\Python_Link.as'

### ISSUE THREAD

**Issue by pavankay** [Linesight-RL/linesight#31]
When I run python scripts/train.py i get a long error but traceback to this. Can you help me, I have  C:\Users\user\Documents\TMInterface\\Plugins\ just I dont have the file Python_link.as.

**Comment by ThatGuyCalledJesse** [comment]
I had this error too, make sure that in the Mod Loader TMInterface is toggled on.

**Comment by pavankay** [comment]
I have the directory just no python_link.as

**Comment by ThatGuyCalledJesse** [comment]
That's quite strange. Did you install TMModLoader and TMInterface correctly?

**Comment by pavankay** [comment]
Will try a reinstall but TMInterface comes with TMmodloader right?

**Comment by ThatGuyCalledJesse** [comment]
If you download it from `https://tomashu.dev/software/tmloader/`, it should indeed come with TMInterface

**Comment by pavankay** [comment]
yes thats where I downloaded it from

**Comment by pavankay** [comment]
After reinstalling it I still don't have the python_link.as

**Comment by pavankay** [comment]
I have figured it out

**Comment by heyitshestia** [comment]
How did you figure it out????
