### ISSUE TITLE
Behaviour always trends towards crashing into walls

### ISSUE THREAD

**Issue by MasonLyons** [Linesight-RL/linesight#4]
I'm using Map 5 to test and no matter if I use the default parameters of change them, the agent always trends towards hugging and crashing into walls.

**Comment by pb4git** [comment]
I think you discussed this directly with Agade. For other who might have the same problem: see the disclaimer in the readme, the default hyperparameters are not optimal for training on Map5.

**Comment by pb4git** [comment]
I'm closing this issue as version 3 has now been released.
