### ISSUE TITLE
Signature of method 'CustomPrioritizedSampler.update_priority()' does not match signature of the base method in class 'PrioritizedSampler'

### ISSUE THREAD

**Issue by Wuodan** [Linesight-RL/linesight#44]
SonarLint shows the warning:
_Signature of method 'CustomPrioritizedSampler.update_priority()' does not match signature of the base method in class 'PrioritizedSampler'_
on trackmania_rl/buffer_utilities.py:223

It seems `*` and `storage` are missing.

**Comment by pb4git** [comment]
Pulled locally to test & integrate.
