### ISSUE TITLE
round() instead of np.round() for ndarray

### ISSUE THREAD

**Issue by Wuodan** [Linesight-RL/linesight#48]
https://github.com/Linesight-RL/linesight/blob/09d84b597e5144f3297116ddfef5b3e3a471c416/trackmania_rl/geometry.py#L55
triggers SonarLint warning:
Expected type '_SupportsRound1[_T]', got 'ndarray[Any, dtype[floating]]' instead

Solution:
Use np.round(), not round() for ndarray.

**Comment by pb4git** [comment]
I don't know what to do here.
On the one hand, c[-1] is a float, not an array. round(c[-1]) is correct.
On the other hand, np.round(c[-1]) is correct too.

Why does SonarQube consider c[-1] is an array?

**Comment by Wuodan** [comment]
I agree with you, Sonar just got confused. Thought there was a slight formal issue but on second thought it's just Sonar.
