### ISSUE TITLE
Not enough memory

### ISSUE THREAD

**Issue by DocOnes** [Linesight-RL/linesight#5]
I've tried the program, everything's fine and I've been able to add the checkpoints to the map, but when I run it an error tells me that I don't have enough available memory and that I need around 14.4 GB. Is it normal to need so much Ram and can I reduce the program's memory usage?

**Comment by pb4git** [comment]
This is weird. I see absolutely no reason why there would be a large memory requirement when collecting checkpoints.
Does the large memory requirement happen when collecting the checkpoints or when training?

**Comment by pb4git** [comment]
Then it is absolutely normal. The code is configured to be compatible with our personnal computers, which have at least 32 GB or RAM.
You can adjust memory requirements in /trackmania_rl/misc.py for your own system.

**Comment by DocOnes** [comment]
Yes i dont have this problem anymore but i have more problem sorry :/. I have an issue with the cuda memory ("CUDA out of memory") I've looked for solutions but haven't found anything and also I haven't looked into this yet but there's a problem when it wants to record a run I think it puts:" DXCamera' object has no attribute 'is_capturing' "
Thanks a lot for helping me !

**Comment by DocOnes** [comment]
The cuda memory problem is fix, i just set the buffer size to 1024 and the DXCamera problem has disappeared so it's ok
Thank you !

**Comment by pb4git** [comment]
I'm closing this issue as version 3 has now been released.
