### ISSUE TITLE
Warning about "Unexpected argument" and `to()`

### ISSUE THREAD

**Issue by Wuodan** [Linesight-RL/linesight#73]
https://github.com/Linesight-RL/linesight/blob/09d84b597e5144f3297116ddfef5b3e3a471c416/trackmania_rl/agents/iqn.py#L465C9-L466C80

SonarLint warnings on both line 465 and 466 are:

> Unexpected argument(s)Possible callees:Module.to(self: Module, device: str | device | int | None = ..., dtype: dtype | None = ..., non_blocking: bool = ...)Module.to(self: Module, dtype: dtype, non_blocking: bool = ...)Module.to(self: Module, tensor: Tensor, non_blocking: bool = ...)

**Comment by pb4git** [comment]
Pulled to integrate
