### ISSUE TITLE
Warning about datatype with max(int, float)

### ISSUE THREAD

**Issue by Wuodan** [Linesight-RL/linesight#85]
https://github.com/Linesight-RL/linesight/blob/09d84b597e5144f3297116ddfef5b3e3a471c416/trackmania_rl/buffer_management.py#L73

Full warning by sonar is:

> Expected type 'int' (matched generic type 'SupportsRichComparisonT ≤: SupportsDunderLT | SupportsDunderGT'), got 'float' instead

**Comment by pb4git** [comment]
Pulled to integrate
